import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";
import React from "react";
// import 'src/i18n/'
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import useLanguageSwitcher from "@/i18n/useLanguageSwitcher";
import Link from "next/link";
type HomeProps = { locale: string };

export async function getStaticProps({ locale }: HomeProps) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
    },
  };
}

export default function Home() {
  const router = useRouter();
  const { pathname, query, asPath, locale: activeLocale } = router;
  const { t } = useTranslation("common");

  const switchh = useLanguageSwitcher;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        {t("links.ten")}
        kdhjkhzkjdhjkzdjkhkz jhzdkjhjkzd kjhzdjk dzkjhkj fzdufjdzkl fkjzldkjfkdz \dzlkjfdjlkzd flzhfnzlndz
        <Link href={{ pathname, query }} as={asPath} locale={"fr"}>Switch</Link>
      </div>
    </>
  );
}
